Cleanup
GIScience/ors-map-client pull request #302
Opened 2022-12-05 16:28 UTC by TheGreatRefrigerator

Move to:
- Webpack 5
- Node 14
- Cypress as testing framework

2022-12-05 16:33 UTC, amoncaldas commented
Not passing in the automated tests https://github.com/GIScience/ors-map-client/actions/runs/3621997759

2022-12-07 10:42 UTC, MichaelsJP requested changes

2022-12-07 12:54 UTC, TheGreatRefrigerator commented on .gitignore
>  !/static/img/.gitkeep
Done

2022-12-07 13:36 UTC, MichaelsJP approved these changes

2022-12-07 13:37 UTC, merged